#!/bin/bash
echo "═══════════════════════════════════════════════════════"
echo "  EAS Keystore Upload - All Information You Need"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "Keystore File Path:"
echo "  android/app/greenhaus-upload-key.keystore"
echo ""
echo "Keystore Password:"
echo "  greenhaus2024!"
echo ""
echo "Key Alias:"
echo "  greenhaus-key"
echo ""
echo "Key Password:"
echo "  greenhaus2024!"
echo ""
echo "═══════════════════════════════════════════════════════"
echo "  Quick Steps:"
echo "═══════════════════════════════════════════════════════"
echo "1. Run: npx eas credentials -p android"
echo "2. Select: production (use ↓↓ then Enter)"
echo "3. Select: 'Keystore: Manage everything...' (Enter)"
echo "4. Choose option to upload/set up keystore"
echo "5. Copy/paste the values above when prompted"
echo ""
echo "File exists: $([ -f android/app/greenhaus-upload-key.keystore ] && echo '✅ YES' || echo '❌ NO')"
echo "═══════════════════════════════════════════════════════"
